version: 0.12.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
environment:
  CI: true
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true
build_script:
- cmd: >-
    npm install -g npm

    npm --version

    node --version

    npm run build-ci
test: off
